include_guard(GLOBAL)
option(VBRECOMP_BITSTRING_DIAGNOSTICS "Count bit-string operations (exclude from throughput builds)" OFF)
set(VBRECOMP_BITSTRING_IMPL "LLE" CACHE STRING "V810 bit-string implementation")
set_property(CACHE VBRECOMP_BITSTRING_IMPL PROPERTY STRINGS LLE HLE)
if(NOT VBRECOMP_BITSTRING_IMPL MATCHES "^(LLE|HLE)$")
    message(FATAL_ERROR "VBRECOMP_BITSTRING_IMPL must be LLE or HLE")
endif()
string(TOLOWER "${VBRECOMP_BITSTRING_IMPL}" _vb_bitstring_suffix)
set(VB_BITSTRING_SOURCE "${CMAKE_CURRENT_LIST_DIR}/src/bitstring_${_vb_bitstring_suffix}.c")
message(STATUS "vbrecomp: bit-string implementation = ${VBRECOMP_BITSTRING_IMPL} (build-fixed)")
